/**
 * Copyright (c) 2024-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  // TITLE_BAR
  public static TITLE_BAR_HEIGHT = 56;

  public static TITLE_BAR_MIN_HEIGHT = 56;

  public static TITLE_BAR_IMAGE_HEIGHT = 24;

  public static TITLE_BAR_IMAGE_WIDTH = 24;

  public static TITLE_BAR_MARGIN_RIGHT = 4;

  // public property style
  public static FLEX_GROW = 1;

  public static MAXIMUM_HEADER_LINES = 2;

  public static DEFAULT_MARGIN_START = 12;

  public static DEFAULT_MARGIN_END = 12;

  public static CLICK_SHADOW_LENGTH = 48;

  public static CONSTRAIN_MIN_HEIGHT = 48;

  //sliding style
  public static SLIDING_THRESHOLD = 160

  //duration style
  public static DURATION_TIME = 300

  public static DURATION_TIME_250 = 250

  // with height style
  public static WIDTH_HEIGHT_FULL_SCREEN = '100%'

  public static NO_RESULT_HEIGHT = '80%'

  // padding style
  public static BOOK_MARK_PADDING_BOTTOM = 50

  // lineHeight style
  public static LINE_HEIGHT_S = 13

  public static LINE_HEIGHT_M = 19

  public static LINE_HEIGHT_L = 21

  // bar max width
  public static GRID_ROW_XS = 4

  public static GRID_ROW_SM = 6

  public static GRID_ROW_MD = 8

  public static GRID_ROW_XS_LG = 10

  // PermissionListView style
  public static OPACITY = 0.2

  public static STROKE_WIDTH_HALF = 0.5

  public static FONT_FAMILY_HARMONY_HEI_TI = 'HarmonyHeiTi'

  // grid useSizeType
  public static GUTTER = 0;

  // line point
  public static START_POINT = -4

  public static END_POINT = 30

  // breakpoints size
  public static XS_BREAKPOINTS_NUMBER = 320;

  public static MD_BREAKPOINTS_NUMBER = 520;

  public static LG_BREAKPOINTS_NUMBER = 840;

  public static XS_BREAKPOINTS = '320vp';

  public static MD_BREAKPOINTS = '520vp';

  public static LG_BREAKPOINTS = '840vp';

  // store key
  public static INIT_APP_INFO_LIST = 'initAppInfoList';

  public static IGNORE_LOCK_SCREEN_PASSWORD_ADVICE_COUNT = 'ignoreLockScreenPasswordAdviceCount';

  public static IGNORE_ADVICE_MAX_COUNT = 2;

  // segmentation button width
  public static BUTTON_BACKGROUND_WIDTH_ONE = 102;

  public static BUTTON_BACKGROUND_WIDTH_TWO = 140;

  public static SEGMENTATION_BUTTON_WIDTH = 448;

  // column row space
  public static DEFAULT_SPACE = 12;

  // domain
  public static DOMAIN = 0x0000;

  public static STORAGE_KEY_SESSION = 'session';

  // device type
  public static DEVICE_TYPE_PC = '2in1';

  public static DEVICE_TYPE_TABLET = 'tablet';

  public static STORAGE_KEY_CURRENT_PAGE_ROUTE = 'currentPageRoute';

  // last %d days
  public static BAR_CHART_DAYS = 3;

  public static ACCESS_RECORD_DAYS = 7;
}