/**
 * Copyright (c) 2024-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class HiSysEventConstant {
  public static BUNDLE_NAME = 'com.ohos.certmanager';

  public static EVENT_DOMAIN = 'PRIVACY_UE';

  public static ACCESS_CLICK_EVENT_NAME = 'SECU_PRIV_ENTRANCE';

  // Settings - Privacy and Security - Privacy Permission List Management Event
  public static MAIN_PERMISSION_LIST_EVENT_NAME = 'MAIN_PERMISSION_LIST';

  // Settings Privacy and Security Permissions Access My Location Information Switch
  public static PERMISSION_PAGE_LOCATION_EVENT_NAME = 'PERMISSION_PAGE_LOCATION';
}